const DATA={
stoff:['Stoff','🧊','Material mit bestimmten Eigenschaften.'],teilchen:['Teilchen','⚛️','Kleine Bausteine der Stoffe.'],energie:['Energie','⚡','Kann aufgenommen oder abgegeben werden.'],temperatur:['Temperatur','🌡️','Gibt an, wie warm etwas ist.'],modell:['Modell','🧩','Vereinfachte Darstellung.'],labor:['Labor','🧪','Ort für Experimente und Nachweise.'],wasser:['Wasser','💧','Wichtiges Lösungsmittel.'],sauerstoff:['Sauerstoff','O₂','Gas, das Verbrennung unterstützt.'],luft:['Luft','🌬️','Gasgemisch der Atmosphäre.'],
stoffeigenschaft:['Stoffeigenschaft','🔎','Merkmal eines Stoffes.'],reinstoff:['Reinstoff','💎','Besteht nur aus einem Stoff.'],stoffgemisch:['Stoffgemisch','🥣','Besteht aus mehreren Stoffen.'],loesung:['Lösung','🫙','Homogenes Gemisch.'],trennverfahren:['Trennverfahren','🧰','Methode zum Trennen von Gemischen.'],filtrieren:['Filtrieren','🧻','Trennt Feststoff und Flüssigkeit.'],destillation:['Destillation','🌫️','Trennt über Siedetemperaturen.'],
teilchenmodell:['Teilchenmodell','🔬','Erklärt Stoffe mit Teilchen.'],atom:['Atom','⚛️','Teilchen eines Elements.'],molekuel:['Molekül','🔗','Mehrere verbundene Atome.'],element:['Element','🧱','Reinstoff aus einer Atomsorte.'],verbindung:['Verbindung','🔗','Stoff aus verschiedenen Atomsorten.'],
reaktion:['Chemische Reaktion','✨','Neue Stoffe entstehen.'],edukt:['Edukt','➡️','Ausgangsstoff einer Reaktion.'],produkt:['Produkt','✅','Stoff, der entsteht.'],schema:['Reaktionsschema','🧾','Edukte → Produkte.'],massenerhaltung:['Massenerhaltung','⚖️','Gesamtmasse bleibt gleich.'],exotherm:['Exotherm','🌞','Energie wird abgegeben.'],endotherm:['Endotherm','🧊','Energie wird aufgenommen.'],
verbrennung:['Verbrennung','🔥','Reaktion mit Sauerstoff.'],oxidation:['Oxidation','🟠','Reaktion mit Sauerstoff.'],kohlenstoffdioxid:['Kohlenstoffdioxid','CO₂','Gas bei vielen Verbrennungen.'],glimmspanprobe:['Glimmspanprobe','🪵','Nachweis für Sauerstoff.'],kalkwasserprobe:['Kalkwasserprobe','🥛','Nachweis für Kohlenstoffdioxid.'],branddreieck:['Branddreieck','🔺','Brennstoff, Sauerstoff, Wärme.'],
atmosphaere:['Atmosphäre','🌍','Gashülle der Erde.'],treibhausgas:['Treibhausgas','🏭','Gas, das Wärme zurückhält.'],methan:['Methan','💨','Starkes Treibhausgas.'],treibhauseffekt:['Treibhauseffekt','🌡️','Treibhausgase halten Wärme zurück.'],erwaermung:['Globale Erwärmung','📈','Langfristige Erwärmung der Erde.'],ozon:['Ozon','O₃','Molekül aus drei Sauerstoffatomen.'],ozonschicht:['Ozonschicht','🛡️','Schutzschicht in der Atmosphäre.'],uv:['UV-Strahlung','☀️','Energiereiche Strahlung der Sonne.'],ozonloch:['Ozonloch','🕳️','Dünnere Stelle in der Ozonschicht.'],
metall:['Metall','🔩','Leitet Wärme und Strom.'],metalloxid:['Metalloxid','🟤','Metall + Sauerstoff.'],rost:['Rost','🟧','Eisenoxid mit Wasser.'],reduktion:['Reduktion','⬇️','Sauerstoff wird entzogen.'],redox:['Redoxreaktion','🔁','Oxidation und Reduktion zusammen.']
};
const START=['stoff','teilchen','energie','temperatur','modell','labor','wasser','sauerstoff','luft'];
const CATEGORY={grund:'🧪 Grundlagen',stoffe:'🥣 Stoffe & Trennen',teil:'⚛️ Teilchenwelt',reak:'✨ Reaktionen',brand:'🔥 Verbrennung & Nachweise',umwelt:'🌍 Treibhauseffekt & Ozonloch',redox:'🔩 Metalle & Redox'};
const CAT={};function cat(c,ids){ids.split(' ').forEach(id=>CAT[id]=c)}
cat('grund','stoff teilchen energie temperatur modell labor wasser sauerstoff luft stoffeigenschaft');cat('stoffe','reinstoff stoffgemisch loesung trennverfahren filtrieren destillation');cat('teil','teilchenmodell atom molekuel element verbindung');cat('reak','reaktion edukt produkt schema massenerhaltung exotherm endotherm');cat('brand','verbrennung oxidation kohlenstoffdioxid glimmspanprobe kalkwasserprobe branddreieck');cat('umwelt','atmosphaere treibhausgas methan treibhauseffekt erwaermung ozon ozonschicht uv ozonloch');cat('redox','metall metalloxid rost reduktion redox');
const RULES={},EXPLAIN={};function key(a,b){return[a,b].sort().join('+')}function rule(a,b,c,e){RULES[key(a,b)]=c;EXPLAIN[c]=e}
rule('stoff','stoff','stoffgemisch','Mehrere Stoffe zusammen ergeben ein Stoffgemisch.');rule('stoff','labor','stoffeigenschaft','Im Labor untersuchst du Stoffeigenschaften.');rule('stoff','teilchen','reinstoff','Ein Reinstoff besteht aus einer Teilchenart.');rule('stoff','wasser','loesung','Ein löslicher Stoff in Wasser bildet eine Lösung.');rule('stoffgemisch','labor','trennverfahren','Gemische kann man mit Trennverfahren trennen.');rule('trennverfahren','wasser','filtrieren','Filtrieren trennt unlösliche Feststoffe von Flüssigkeiten.');rule('trennverfahren','temperatur','destillation','Destillation nutzt unterschiedliche Siedetemperaturen.');
rule('stoff','modell','teilchenmodell','Das Teilchenmodell erklärt Stoffe mit kleinen Teilchen.');rule('teilchen','teilchen','atom','Einzelne chemische Teilchen können Atome sein.');rule('atom','atom','molekuel','Mehrere Atome können ein Molekül bilden.');rule('atom','stoff','element','Ein Element besteht aus einer Atomsorte.');rule('element','element','verbindung','Aus verschiedenen Elementen entstehen Verbindungen.');
rule('stoff','energie','reaktion','Bei chemischen Reaktionen werden Stoffe umgewandelt.');rule('reaktion','stoff','edukt','Ausgangsstoffe heißen Edukte.');rule('edukt','reaktion','produkt','Bei einer Reaktion entstehen Produkte.');rule('reaktion','modell','schema','Ein Schema zeigt Edukte und Produkte.');rule('edukt','produkt','massenerhaltung','Die Gesamtmasse bleibt erhalten.');rule('reaktion','energie','exotherm','Wenn Energie abgegeben wird, ist die Reaktion exotherm.');rule('reaktion','temperatur','endotherm','Wenn Energie aufgenommen wird, ist die Reaktion endotherm.');
rule('sauerstoff','temperatur','verbrennung','Verbrennungen brauchen Sauerstoff und genügend Wärme.');rule('stoff','sauerstoff','oxidation','Reaktionen mit Sauerstoff heißen Oxidationen.');rule('verbrennung','stoff','kohlenstoffdioxid','Bei vielen Verbrennungen entsteht Kohlenstoffdioxid.');rule('sauerstoff','labor','glimmspanprobe','Die Glimmspanprobe weist Sauerstoff nach.');rule('kohlenstoffdioxid','labor','kalkwasserprobe','Die Kalkwasserprobe weist Kohlenstoffdioxid nach.');rule('verbrennung','modell','branddreieck','Das Branddreieck erklärt, was Feuer braucht.');
rule('luft','modell','atmosphaere','Die Atmosphäre ist die Gashülle der Erde.');rule('luft','sauerstoff','atmosphaere','Sauerstoff ist ein Bestandteil der Atmosphäre.');rule('kohlenstoffdioxid','luft','treibhausgas','Kohlenstoffdioxid wirkt in der Luft als Treibhausgas.');rule('stoff','treibhausgas','methan','Methan ist ein starkes Treibhausgas.');rule('treibhausgas','energie','treibhauseffekt','Treibhausgase halten einen Teil der Wärme zurück.');rule('treibhauseffekt','kohlenstoffdioxid','erwaermung','Mehr Treibhausgase können die Erde erwärmen.');rule('sauerstoff','energie','ozon','Aus Sauerstoff kann Ozon entstehen.');rule('ozon','atmosphaere','ozonschicht','Ozon bildet in der Atmosphäre die Ozonschicht.');rule('ozonschicht','energie','uv','Die Ozonschicht schützt vor viel UV-Strahlung.');rule('ozonschicht','stoff','ozonloch','Bestimmte Stoffe können die Ozonschicht ausdünnen.');rule('ozonloch','uv','ozonschicht','Beim Ozonloch ist die Schutzwirkung geschwächt.');
rule('metall','sauerstoff','metalloxid','Metalle reagieren mit Sauerstoff zu Metalloxiden.');rule('metalloxid','wasser','rost','Rost entsteht bei Eisen durch Sauerstoff und Wasser.');rule('metalloxid','energie','reduktion','Bei einer Reduktion wird Sauerstoff entzogen.');rule('oxidation','reduktion','redox','Oxidation und Reduktion laufen zusammen ab.');
const FORMEL={verbrennung:'CH₄ + 2 O₂ → CO₂ + 2 H₂O',oxidation:'2 Mg + O₂ → 2 MgO',kohlenstoffdioxid:'C + O₂ → CO₂',metalloxid:'2 Cu + O₂ → 2 CuO',rost:'4 Fe + 3 O₂ → 2 Fe₂O₃',reduktion:'2 CuO + C → 2 Cu + CO₂',redox:'2 CuO + C → 2 Cu + CO₂',ozon:'3 O₂ → 2 O₃',molekuel:'2 H → H₂'};
const WARUM={reinstoff:'Merke: Ein Reinstoff besteht aus nur einer Teilchenart, z. B. destilliertes Wasser.',stoffgemisch:'Alltag: Luft, Salzwasser und Granit sind Stoffgemische.',loesung:'Alltag: Zucker im Tee „verschwindet" nicht – er verteilt sich gleichmäßig zur Lösung.',filtrieren:'Alltag: Der Kaffeefilter trennt das Pulver von der Flüssigkeit.',destillation:'Alltag: So gewinnt man Trinkwasser aus Salzwasser.',atom:'Merke: Atome sind die kleinsten Bausteine eines Elements.',molekuel:'Alltag: Ein Wassermolekül besteht aus zwei H- und einem O-Atom.',verbindung:'Merke: In einer Verbindung sind verschiedene Atomsorten fest verbunden.',massenerhaltung:'Merke: Es geht nichts verloren – nur die Anordnung der Atome ändert sich.',exotherm:'Alltag: Ein Lagerfeuer gibt Wärme ab – das ist exotherm.',endotherm:'Alltag: Beim Auflösen mancher Salze wird das Wasser kälter – das ist endotherm.',verbrennung:'Merke: Ohne Sauerstoff keine Verbrennung – darum erstickt ein Glas die Kerzenflamme.',oxidation:'Merke: Oxidation ist die Reaktion eines Stoffes mit Sauerstoff.',kohlenstoffdioxid:'Alltag: Du atmest CO₂ aus – es trübt Kalkwasser.',glimmspanprobe:'Merke: Glühender Span flammt auf → Sauerstoff ist vorhanden.',kalkwasserprobe:'Merke: Kalkwasser trübt sich → Kohlenstoffdioxid ist vorhanden.',branddreieck:'Merke: Brennstoff, Sauerstoff, Wärme – nimm eines weg, und das Feuer erlischt.',treibhauseffekt:'Alltag: Wie im Auto in der Sonne – Wärme kommt rein, aber schlecht wieder raus.',erwaermung:'Merke: Mehr Treibhausgase → wärmeres Klima.',ozonschicht:'Merke: Die Ozonschicht ist unser natürlicher Sonnenschutz gegen UV-Strahlung.',ozonloch:'Alltag: FCKW aus alten Spraydosen haben die Ozonschicht ausgedünnt.',rost:'Alltag: Darum rosten Fahrräder im Regen – Eisen + Sauerstoff + Wasser.',reduktion:'Merke: Reduktion ist die Umkehrung der Oxidation – Sauerstoff wird entzogen.',redox:'Merke: Einer gibt ab, einer nimmt auf – Oxidation und Reduktion laufen gleichzeitig.'};
const FAILHINT={};function fail(a,b,t){FAILHINT[key(a,b)]=t}
fail('sauerstoff','wasser','Sauerstoff löst sich in Wasser, aber es entsteht kein neuer Stoff – das ist keine chemische Reaktion.');fail('wasser','energie','Wasser + Energie verdampft nur. Das ist eine Zustandsänderung, keine chemische Reaktion.');fail('sauerstoff','sauerstoff','Zwei Sauerstoff-Teilchen allein ergeben noch nichts Neues. Tipp: Sauerstoff + Energie kann Ozon bilden.');fail('kohlenstoffdioxid','wasser','CO₂ löst sich in Wasser (Sprudel!). Für den Nachweis brauchst du aber Kalkwasser im Labor.');fail('metall','wasser','Hier fehlt ein Schritt: Lass das Metall erst mit Sauerstoff zu einem Metalloxid reagieren.');fail('luft','energie','Luft ist ein Gemisch – für eine Reaktion brauchst du einen bestimmten Stoff, z. B. Sauerstoff.');
const MISSIONS=[['m1','Grundlagen','Finde Stoffgemisch, Reinstoff, Teilchenmodell und Atom.',['stoffgemisch','reinstoff','teilchenmodell','atom']],['m2','Stoffe trennen','Entdecke Lösung und Trennverfahren.',['loesung','trennverfahren','filtrieren','destillation']],['m3','Teilchenwelt','Baue Atom → Molekül → Element → Verbindung.',['atom','molekuel','element','verbindung']],['m4','Reaktion','Erkläre Edukte, Produkte und Massenerhaltung.',['reaktion','edukt','produkt','schema','massenerhaltung']],['m5','Verbrennung','Verbinde Sauerstoff, Oxidation und Nachweise.',['verbrennung','oxidation','kohlenstoffdioxid','glimmspanprobe','kalkwasserprobe','branddreieck']],['m6','Treibhauseffekt','Erkläre Atmosphäre, Treibhausgase und Erwärmung.',['atmosphaere','treibhausgas','methan','treibhauseffekt','erwaermung']],['m7','Ozonloch','Verbinde Ozon, Ozonschicht und UV-Strahlung.',['ozon','ozonschicht','uv','ozonloch']],['m8','Redox','Finde Metalloxid, Rost, Reduktion und Redoxreaktion.',['metall','metalloxid','rost','reduktion','redox']]];
const MISSION_CAT={m1:'grund',m2:'stoffe',m3:'teil',m4:'reak',m5:'brand',m6:'umwelt',m7:'umwelt',m8:'redox'};
const SEEDS={stoffe:['stoffgemisch','trennverfahren'],teil:['atom','molekuel','element'],reak:['reaktion','edukt'],brand:['verbrennung','branddreieck'],umwelt:['atmosphaere','treibhausgas','ozon','uv'],redox:['metall','metalloxid']};
const SAVE='little-chemie8-save-v4',COINS='little-chemie8-coins-v4',QUIZ_SEEN='little-chemie8-quiz-seen-v1',XP='little-chemie8-xp-v1';let deck=[...START],selected=null,activeCat='grund',coins=5,lastRank='',xp=0,combo=0;
const $=s=>document.querySelector(s);const grid=$('#grid'),msg=$('#msg'),A=$('#slotA'),B=$('#slotB'),R=$('#slotR');
function item(id){return DATA[id]}function icon(id){return item(id)[1]}function name(id){return item(id)[0]}function info(id){return item(id)[2]}
function load(){try{deck=[...new Set([...START,...JSON.parse(localStorage.getItem(SAVE)||'[]').filter(id=>DATA[id])])];const stored=localStorage.getItem(COINS);coins=stored===null?5:Number(stored);if(!Number.isFinite(coins))coins=5;const sx=localStorage.getItem(XP);xp=sx===null?0:Number(sx);if(!Number.isFinite(xp)||xp<0)xp=0}catch(e){deck=[...START];coins=5;xp=0}combo=0;unlock(false)}
function save(){localStorage.setItem(SAVE,JSON.stringify(deck.filter(id=>!START.includes(id))));localStorage.setItem(COINS,String(coins));localStorage.setItem(XP,String(xp));schedulePush()}
const IDENT='schoolapp-ident-v1',GAME='chemie8';let cloudOn=false,ident=null,pushTimer=null;
function currentState(){return{deck:deck.filter(id=>!START.includes(id)),coins,xp}}
function applyState(s){if(!s||typeof s!=='object')return;deck=[...new Set([...START,...(Array.isArray(s.deck)?s.deck.filter(id=>DATA[id]):[])])];coins=Number.isFinite(s.coins)?s.coins:5;xp=Number.isFinite(s.xp)&&s.xp>=0?s.xp:0;combo=0;save()}
function getIdent(){try{return JSON.parse(localStorage.getItem(IDENT)||'null')}catch(e){return null}}
function setIdent(i){ident=i;localStorage.setItem(IDENT,JSON.stringify(i))}
async function cloudAvailable(){try{const c=new AbortController(),t=setTimeout(()=>c.abort(),2500);const r=await fetch('/api/ping',{signal:c.signal});clearTimeout(t);return r.ok}catch(e){return false}}
async function fetchProgress(id){try{const r=await fetch('/api/progress?code='+encodeURIComponent(id.code)+'&name='+encodeURIComponent(id.name)+'&game='+encodeURIComponent(GAME)+'&pw='+encodeURIComponent(id.pw||''));let j={};try{j=await r.json()}catch(e){}return{status:r.status,ok:r.ok,state:j.state||null,error:j.error}}catch(e){return{status:0,ok:false,state:null}}}
function freshState(){deck=[...START];coins=5;xp=0;combo=0;save()}
function hydrate(res){if(res&&res.state&&Array.isArray(res.state.deck))applyState(res.state);else freshState()}
function finishCloud(){setAccountUI();unlock(true);lastRank=rank();resetSlots();render()}
async function push(){if(!cloudOn||!ident)return;try{await fetch('/api/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:ident.code,name:ident.name,game:GAME,pw:ident.pw||'',state:currentState()})})}catch(e){}}
function schedulePush(){if(!cloudOn||!ident)return;clearTimeout(pushTimer);pushTimer=setTimeout(push,800)}
function setAccountUI(){const a=$('#account');if(!a)return;if(cloudOn&&ident){a.hidden=false;a.textContent='👤 '+ident.name;a.title='Klasse: '+ident.code+' · tippen zum Wechseln';a.onclick=logout}else a.hidden=true}
// Der Login kommt vom Portal: zurück zum Portal (ident wird dort gesetzt).
function logout(){localStorage.removeItem(IDENT);location.href='/'}
// Kein eigener Login mehr im Spiel – die Anmeldung erfolgt im Portal (index.html).
// Ohne gültige ident im localStorage geht es zurück zum Portal.
async function initCloud(){if(new URLSearchParams(location.search).get('test')==='1'){cloudOn=false;setAccountUI();toast('🧪 Testmodus – Fortschritt wird nicht gespeichert');return}cloudOn=await cloudAvailable();if(!cloudOn){setAccountUI();return}ident=getIdent();if(!ident||!ident.code||!ident.name){location.href='/';return}const res=await fetchProgress(ident);if(res.status===403){localStorage.removeItem(IDENT);location.href='/';return}hydrate(res);finishCloud();toast('☁️ Angemeldet als '+ident.name)}
function setSlot(el,id,label){el.className='slot'+(id?' on':'');el.innerHTML=id?`${icon(id)}<span>${name(id)}</span><small>${info(id)}</small>`:`❔<span>${label}</span>`}
function setResult(id,ok){R.className='slot '+(ok?'ok':'bad');R.innerHTML=id?`${icon(id)}<span>${name(id)}</span>`:'✨<span>Ergebnis</span>'}
function resetSlots(){setSlot(A,null,'1. Begriff');setSlot(B,null,'2. Begriff');setResult(null,true);render()}
function missionVisible(m){const cat=MISSION_CAT[m[0]]||'grund';return cat==='grund'||deck.some(id=>CAT[id]===cat)}
function doneCount(){return MISSIONS.filter(m=>missionVisible(m)&&m[3].every(id=>deck.includes(id))).length}
function rank(){const n=doneCount();if(n>=8)return'Chemie-Meister';if(n>=6)return'Umwelt-Profi';if(n>=4)return'Reaktions-Profi';if(n>=2)return'Chemie-Starter';return'Starter'}
function progress(cat){return deck.filter(id=>CAT[id]===cat).length+' / '+Object.keys(CAT).filter(id=>CAT[id]===cat).length}
function levelOf(x){let lvl=1,need=120,acc=0;while(x>=acc+need){acc+=need;lvl++;need=Math.round(need*1.3)}return{lvl,into:x-acc,need}}
function comboMult(){return Math.max(1,Math.min(5,1+Math.floor((combo-1)/2)))}
function addXp(n){const before=levelOf(xp).lvl;xp+=n;const after=levelOf(xp).lvl;if(after>before){const bonus=after*3;coins+=bonus;toast('🎉 Level '+after+' erreicht! +'+bonus+' 🪙');confetti();setTimeout(confetti,180)}}
function unlock(store){let unlocked=[];function add(cat,cond){if(!cond)return;(SEEDS[cat]||[]).forEach(id=>{if(!deck.includes(id)){deck.push(id);if(!unlocked.includes(cat))unlocked.push(cat)}})}add('stoffe',deck.includes('stoffgemisch')||deck.includes('loesung'));add('teil',deck.includes('teilchenmodell')||deck.includes('atom'));add('reak',deck.includes('reaktion')||deck.includes('produkt'));add('brand',deck.includes('verbrennung')||deck.includes('oxidation'));add('umwelt',deck.includes('kohlenstoffdioxid')||deck.includes('atmosphaere')||deck.includes('ozon'));add('redox',deck.includes('oxidation')||deck.includes('metalloxid')||deck.includes('redox'));if(store&&unlocked.length)save();return unlocked}
function renderMissions(){const box=$('#missions');box.innerHTML='';const visible=MISSIONS.filter(missionVisible);if(!visible.length){box.innerHTML='<article class="mission"><div class="mt">🔒 Missionen gesperrt</div><div class="mi">Entdecke zuerst neue Begriffe, dann erscheinen neue Missionen.</div></article>';return}visible.forEach(m=>{const found=m[3].filter(id=>deck.includes(id)).length,ok=found===m[3].length;const el=document.createElement('article');el.className='mission '+(ok?'done':'');el.dataset.cat=MISSION_CAT[m[0]]||'grund';el.innerHTML=`<div class="mt">${ok?'✅':'🎯'} Mission: ${m[1]}</div><div class="mi">${m[2]}</div><b>${found} / ${m[3].length} entdeckt</b><div class="targets">${m[3].map(id=>`<span class="${deck.includes(id)?'done':''}">${icon(id)} ${name(id)}</span>`).join('')}</div>`;box.appendChild(el)})}
function renderLabNote(){const note=$('#labnote');if(!note)return;const n=doneCount(),total=MISSIONS.filter(missionVisible).length;note.innerHTML=`Du hast <b>${deck.length}</b> Fachkarten und <b>${n} von ${total}</b> sichtbaren Missionen geschafft.`;note.hidden=false}
function render(){const cats=Object.keys(CATEGORY).filter(c=>deck.some(id=>CAT[id]===c));if(!cats.includes(activeCat))activeCat=cats[0]||'grund';grid.innerHTML=`<div class="tabs">${cats.map(c=>`<button class="tab ${c===activeCat?'active':''}" data-cat="${c}">${CATEGORY[c]} · ${progress(c)}</button>`).join('')}</div><div class="head" data-cat="${activeCat}">${CATEGORY[activeCat]} <span>${progress(activeCat)}</span></div>`;grid.querySelectorAll('.tab').forEach(btn=>btn.onclick=()=>{activeCat=btn.dataset.cat;toast('Kategorie: '+CATEGORY[activeCat]);render()});const search=$('#search').value.toLowerCase();const cards=deck.filter(id=>CAT[id]===activeCat&&(!search||name(id).toLowerCase().includes(search)));if(!cards.length){grid.insertAdjacentHTML('beforeend','<div class="empty">Keine Karte gefunden.</div>')}cards.forEach(id=>{const el=document.createElement('article');el.className='card '+(selected===id?'sel':'');el.dataset.cat=CAT[id]||'grund';el.innerHTML=`<div class="sym">${icon(id)}</div><div class="name">${name(id)}</div><div class="info">${info(id)}</div>`;el.onclick=()=>choose(id);grid.appendChild(el)});$('#count').textContent=deck.length+' / '+Object.keys(DATA).length;$('#badge').textContent=rank();$('#coins').textContent='🪙 '+coins;const li=levelOf(xp);$('#level').textContent='⭐ Lvl '+li.lvl;$('#progressBar').style.width=Math.round(li.into/li.need*100)+'%';const cb=$('#combo');if(cb){if(combo>1){cb.textContent='🔥 Combo x'+comboMult();cb.hidden=false}else cb.hidden=true}renderMissions();renderLabNote();const r=rank();if(lastRank&&lastRank!==r){toast('🏅 Neues Abzeichen: '+r);confetti()}lastRank=r}
function choose(id){if(!selected){selected=id;setSlot(A,id);setSlot(B,null,'2. Begriff');setResult(null,true);msg.innerHTML=`<b>${icon(id)} ${name(id)}</b>: ${info(id)}<br>Wähle jetzt einen zweiten Begriff.`;render();return}setSlot(B,id);combine(selected,id);selected=null}
function combine(a,b){const result=RULES[key(a,b)];if(!result){if(combo>1)toast('💥 Combo beendet');combo=0;setResult(null,false);msg.innerHTML=smartFail(a,b);render();setTimeout(resetSlots,1050);return}combo++;const mult=comboMult();const isNew=!deck.includes(result);let gained=0;if(isNew){deck.push(result);gained=2*mult;coins+=gained;addXp(12);save()}const formula=`${name(a)} + ${name(b)} = ${name(result)}`;const explain=EXPLAIN[result]||info(result);setResult(result,true);const chem=FORMEL[result]?`<br><span class="chemformula">⚗️ ${FORMEL[result]}</span>`:'';const why=WARUM[result]?`<br><span class="why">💡 ${WARUM[result]}</span>`:'';const comboLine=mult>1?`<br><span class="comboTag">🔥 Combo x${mult}</span>`:'';const coinLine=isNew?`<br>🪙 +${gained} Münzen${mult>1?' · Combo-Bonus!':''} · +12 XP`:'';msg.innerHTML=`<b>${formula}</b>${comboLine}${chem}<br>${explain}${why}${coinLine}`;const unlocked=unlock(true);if(isNew){showUnlock(result,formula,explain);confetti()}setTimeout(()=>{resetSlots();activeCat=CAT[result]||activeCat;render();if(unlocked.length)toast('🔓 Freigeschaltet: '+unlocked.map(c=>CATEGORY[c]).join(', '))},1350)}
function smartFail(a,b){const h=FAILHINT[key(a,b)];if(h)return'🔎 '+h;if(CAT[a]!==CAT[b])return`Gute Idee. Die Begriffe liegen in <b>${CATEGORY[CAT[a]]}</b> und <b>${CATEGORY[CAT[b]]}</b>. Suche vielleicht erst einen Zwischenschritt.`;return'Noch keine passende Kombination. Denke an: Stoff, Teilchen, Reaktion, Nachweis oder Umweltzusammenhang.'}
function showUnlock(id,formula,explain){$('#pe').textContent=icon(id);$('#pt').textContent=name(id);$('#pf').textContent=formula;const chem=$('#pchem'),f=FORMEL[id];if(f){chem.textContent='⚗️ '+f;chem.hidden=false}else chem.hidden=true;$('#px').textContent=explain;const why=$('#pwhy'),w=WARUM[id];if(w){why.textContent='💡 '+w;why.hidden=false}else why.hidden=true;$('#pop').classList.add('show')}
function hint(){if(coins<3){msg.innerHTML='Ein Tipp kostet <b>3 Münzen</b>. Entdecke neue Begriffe oder spiele Chemie-Blitz.';return}const possible=[];for(let i=0;i<deck.length;i++)for(let j=i;j<deck.length;j++){const c=RULES[key(deck[i],deck[j])];if(c&&!deck.includes(c))possible.push([deck[i],deck[j]])}if(!possible.length){msg.textContent='Im Moment gibt es keinen neuen Tipp.';return}coins-=3;save();const pair=possible[Math.floor(Math.random()*possible.length)];msg.innerHTML=`💡 Probiere <b>${icon(pair[0])} ${name(pair[0])}</b> + <b>${icon(pair[1])} ${name(pair[1])}</b>.`;render()}
function reset(){localStorage.removeItem(SAVE);localStorage.removeItem(COINS);localStorage.removeItem(QUIZ_SEEN);localStorage.removeItem(XP);deck=[...START];coins=5;xp=0;combo=0;selected=null;activeCat='grund';$('#search').value='';save();resetSlots();msg.innerHTML='Neustart: Du beginnst mit <b>9 Grundbegriffen</b> und <b>5 Münzen</b>.'}
const QUESTIONS=[['Was weist die Glimmspanprobe nach?','Sauerstoff',['Sauerstoff','Kohlenstoffdioxid','Wasser']],['Was ist eine Reaktion mit Sauerstoff?','Oxidation',['Oxidation','Diffusion','Destillation']],['Welches Gas entsteht bei vielen Verbrennungen?','Kohlenstoffdioxid',['Kohlenstoffdioxid','Sauerstoff','Ozon']],['Was ist ein Treibhausgas?','Kohlenstoffdioxid',['Kohlenstoffdioxid','Metalloxid','Eis']],['Was hält beim Treibhauseffekt Wärme zurück?','Treibhausgase',['Treibhausgase','Filterpapier','Metalle']],['Was schützt vor viel UV-Strahlung?','Ozonschicht',['Ozonschicht','Branddreieck','Kalkwasser']],['Was sind Oxidation und Reduktion zusammen?','Redoxreaktion',['Redoxreaktion','Aggregatzustand','Lösung']],['Wie heißen Ausgangsstoffe einer Reaktion?','Edukte',['Edukte','Produkte','Nachweise']],['Welche Probe weist Kohlenstoffdioxid nach?','Kalkwasserprobe',['Kalkwasserprobe','Glimmspanprobe','Siedepunktprobe']],['Was entsteht aus Metall und Sauerstoff?','Metalloxid',['Metalloxid','Reinstoff','Lösung']],['Was beschreibt die Massenerhaltung?','Die Gesamtmasse bleibt gleich',['Die Gesamtmasse bleibt gleich','Die Temperatur bleibt immer gleich','Es entsteht immer Sauerstoff']],['Was ist Ozon?','Ein Molekül aus drei Sauerstoffatomen',['Ein Molekül aus drei Sauerstoffatomen','Ein Metalloxid','Ein Trennverfahren']]];
function shuffle(a){return a.map(v=>[Math.random(),v]).sort((x,y)=>x[0]-y[0]).map(x=>x[1])}
function nextQuizQuestions(count=3){let seen=[];try{seen=JSON.parse(localStorage.getItem(QUIZ_SEEN)||'[]').filter(i=>Number.isInteger(i)&&i>=0&&i<QUESTIONS.length)}catch(e){seen=[]}let open=QUESTIONS.map((_,i)=>i).filter(i=>!seen.includes(i));if(open.length<count){seen=[];open=QUESTIONS.map((_,i)=>i);toast('🔁 Fragenpool neu gemischt.')}const picked=shuffle(open).slice(0,count);localStorage.setItem(QUIZ_SEEN,JSON.stringify([...new Set([...seen,...picked])]));return picked.map(i=>QUESTIONS[i])}
function quiz(){const qs=nextQuizQuestions(3);let i=0,ok=0;$('#game').classList.add('show');function ask(){const q=qs[i];$('#gs').textContent=`Frage ${i+1}/3 · richtig: ${ok}`;$('#gq').innerHTML='<h3>'+q[0]+'</h3>';$('#ga').innerHTML='';shuffle(q[2]).forEach(answer=>{const btn=document.createElement('button');btn.textContent=answer;btn.onclick=()=>{if(answer===q[1]){ok++;coins++;addXp(6);btn.className='r';$('#gs').textContent='✅ Richtig! +1 Münze · +6 XP'}else{btn.className='w';$('#gs').textContent='❌ Richtig wäre: '+q[1]}Array.from($('#ga').children).forEach(c=>c.disabled=true);setTimeout(()=>{i++;i<3?ask():finish()},850)};$('#ga').appendChild(btn)})}function finish(){if(ok===3){coins+=2;addXp(15);$('#gs').innerHTML='🏆 Perfekt! +2 Bonus-Münzen · +15 XP'}else $('#gs').textContent=`Fertig: ${ok}/3 richtig.`;save();render();if(ok===3)confetti();$('#gq').innerHTML='';$('#ga').innerHTML='<button onclick="quiz()">Nochmal spielen</button>'}ask()}
function confetti(){['🧪','⚛️','✨','🌍','🔥','🔬'].forEach((x,i)=>{setTimeout(()=>{const el=document.createElement('div');el.className='confetti';el.textContent=x;el.style.left=Math.random()*96+'vw';document.body.appendChild(el);setTimeout(()=>el.remove(),1500)},i*80)})}
function toast(text){const old=document.querySelector('.toast');if(old)old.remove();const el=document.createElement('div');el.className='toast';el.textContent=text;document.body.appendChild(el);setTimeout(()=>el.remove(),2300)}
function closeModals(){document.querySelectorAll('.modal').forEach(m=>m.classList.remove('show'))}
document.addEventListener('click',e=>{if(e.target.matches('[data-close]'))e.target.closest('.modal').classList.remove('show');if(e.target.classList.contains('modal'))e.target.classList.remove('show')});
$('#hint').onclick=hint;$('#reset').onclick=reset;$('#quiz').onclick=quiz;$('#search').oninput=render;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModals()});
load();lastRank=rank();resetSlots();msg.innerHTML='Starte mit <b>9 Grundbegriffen</b>. Neue Missionen erscheinen erst, wenn du den passenden Bereich freischaltest.';initCloud();