const DATA={
leben:['Leben','🌱','Lebewesen wachsen, atmen und vermehren sich.'],zelle:['Zelle','🔬','Kleinste Einheit des Lebens.'],wasser:['Wasser','💧','Lebenswichtiges Lösungs- und Transportmittel.'],licht:['Sonnenlicht','☀️','Energiequelle für Pflanzen.'],energie:['Energie','⚡','Wird für alle Lebensvorgänge gebraucht.'],sauerstoff:['Sauerstoff','O₂','Gas, das Lebewesen veratmen.'],kohlenstoffdioxid:['Kohlenstoffdioxid','CO₂','Gas für die Photosynthese.'],naehrstoff:['Nährstoff','🍎','Liefert Baustoffe und Energie.'],mikroskop:['Mikroskop','🔬','Macht Zellen sichtbar.'],
zellmembran:['Zellmembran','🧫','Grenze der Zelle, regelt den Stoffaustausch.'],zellkern:['Zellkern','⚫','Steuerzentrale mit der Erbinformation.'],zytoplasma:['Zytoplasma','🌫️','Wässrige Füllmasse der Zelle.'],mitochondrium:['Mitochondrium','🔋','Kraftwerk der Zelle (Zellatmung).'],chloroplast:['Chloroplast','🟢','Ort der Photosynthese.'],zellwand:['Zellwand','🧱','Stützt Pflanzenzellen.'],vakuole:['Vakuole','🫧','Speicher in Pflanzenzellen.'],pflanzenzelle:['Pflanzenzelle','🌿','Zelle mit Zellwand, Chloroplasten und Vakuole.'],tierzelle:['Tierzelle','🐾','Zelle ohne Zellwand und Chloroplasten.'],
chlorophyll:['Chlorophyll','💚','Grüner Farbstoff, fängt Licht ein.'],photosynthese:['Photosynthese','🌞','Aus Licht, CO₂ und Wasser entstehen Glucose und O₂.'],glucose:['Glucose','🍬','Traubenzucker als Energieträger.'],staerke:['Stärke','🥔','Speicherform der Glucose.'],zellatmung:['Zellatmung','🫁','Glucose + O₂ liefern Energie.'],wurzel:['Wurzel','🌱','Nimmt Wasser und Nährsalze auf.'],blatt:['Blatt','🍃','Ort der Photosynthese.'],spross:['Spross','🌾','Stängel mit Blättern.'],
verdauung:['Verdauung','😋','Zerlegt Nahrung in Nährstoffe.'],atmung:['Atmung','🌬️','Nimmt O₂ auf und gibt CO₂ ab.'],lunge:['Lunge','🫁','Organ des Gasaustausches.'],blut:['Blut','🩸','Transportflüssigkeit des Körpers.'],herz:['Herz','❤️','Pumpe des Blutkreislaufs.'],blutkreislauf:['Blutkreislauf','🔁','Transportiert Stoffe im Körper.'],niere:['Niere','🫘','Filtert das Blut.'],
produzent:['Produzent','🌳','Pflanze, die Biomasse aufbaut.'],konsument:['Konsument','🦌','Tier, das andere Lebewesen frisst.'],destruent:['Destruent','🍄','Zersetzt totes Material zu Nährstoffen.'],nahrungskette:['Nahrungskette','🔗','Produzent → Konsument → …'],biozoenose:['Biozönose','🐝','Lebensgemeinschaft aller Arten.'],biotop:['Biotop','🪨','Lebensraum der Lebewesen.'],oekosystem:['Ökosystem','🏞️','Lebewesen und Lebensraum im Zusammenspiel.'],
art:['Art','🦋','Lebewesen, die fruchtbare Nachkommen zeugen.'],wirbeltier:['Wirbeltier','🐟','Tier mit Wirbelsäule.'],wirbellose:['Wirbellose','🐌','Tier ohne Wirbelsäule.'],saeugetier:['Säugetier','🐕','Wirbeltier, das seine Jungen säugt.'],anpassung:['Anpassung','🦎','Merkmal passend zum Lebensraum.'],vielfalt:['Biodiversität','🌈','Vielfalt der Arten im Ökosystem.']
};
const START=['leben','zelle','wasser','licht','energie','sauerstoff','kohlenstoffdioxid','naehrstoff','mikroskop'];
const CATEGORY={grund:'🌱 Grundlagen',zelle:'🔬 Zelle',pflanze:'🌿 Pflanzen & Photosynthese',mensch:'🫀 Der Mensch',oeko:'🏞️ Ökologie',vielfalt:'🦋 Vielfalt der Lebewesen'};
const CAT={};function cat(c,ids){ids.split(' ').forEach(id=>CAT[id]=c)}
cat('grund','leben zelle wasser licht energie sauerstoff kohlenstoffdioxid naehrstoff mikroskop');cat('zelle','zellmembran zellkern zytoplasma mitochondrium chloroplast zellwand vakuole pflanzenzelle tierzelle');cat('pflanze','chlorophyll photosynthese glucose staerke zellatmung wurzel blatt spross');cat('mensch','verdauung atmung lunge blut herz blutkreislauf niere');cat('oeko','produzent konsument destruent nahrungskette biozoenose biotop oekosystem');cat('vielfalt','art wirbeltier wirbellose saeugetier anpassung vielfalt');
const RULES={},EXPLAIN={};function key(a,b){return[a,b].sort().join('+')}function rule(a,b,c,e){RULES[key(a,b)]=c;EXPLAIN[c]=e}
rule('zelle','zelle','zellmembran','Jede Zelle ist von einer Zellmembran umgeben.');rule('zelle','mikroskop','zellkern','Unterm Mikroskop erkennt man den Zellkern.');rule('zelle','wasser','zytoplasma','Das Zytoplasma ist die wässrige Füllmasse der Zelle.');rule('zelle','energie','mitochondrium','Mitochondrien liefern Energie – die Kraftwerke der Zelle.');rule('zelle','licht','chloroplast','Chloroplasten nutzen Licht für die Photosynthese.');rule('zellmembran','zelle','zellwand','Pflanzenzellen haben außen zusätzlich eine stützende Zellwand.');rule('zelle','naehrstoff','vakuole','Die Vakuole speichert Stoffe in der Pflanzenzelle.');rule('chloroplast','zellwand','pflanzenzelle','Eine Pflanzenzelle hat Zellwand, Chloroplasten und Vakuole.');rule('zellkern','zellmembran','tierzelle','Eine Tierzelle hat Zellkern und Membran, aber keine Zellwand.');
rule('chloroplast','licht','chlorophyll','Chlorophyll ist der grüne Farbstoff, der Licht einfängt.');rule('chlorophyll','kohlenstoffdioxid','photosynthese','Mit Chlorophyll, CO₂ und Wasser läuft die Photosynthese.');rule('photosynthese','wasser','glucose','Bei der Photosynthese entsteht der Zucker Glucose.');rule('glucose','glucose','staerke','Viele Glucose-Bausteine ergeben Stärke als Speicher.');rule('glucose','sauerstoff','zellatmung','Bei der Zellatmung wird Glucose mit O₂ zu Energie abgebaut.');rule('pflanzenzelle','wasser','wurzel','Wurzeln nehmen Wasser und Nährsalze auf.');rule('pflanzenzelle','licht','blatt','Im Blatt findet die Photosynthese statt.');rule('wurzel','blatt','spross','Der Spross trägt die Blätter und verbindet sie mit der Wurzel.');
rule('naehrstoff','wasser','verdauung','Die Verdauung zerlegt Nahrung in Nährstoffe.');rule('leben','sauerstoff','atmung','Lebewesen nehmen bei der Atmung Sauerstoff auf.');rule('atmung','sauerstoff','lunge','In der Lunge gelangt Sauerstoff ins Blut.');rule('tierzelle','wasser','blut','Blut transportiert Stoffe mit roten Blutzellen.');rule('blut','energie','herz','Das Herz pumpt das Blut durch den Körper.');rule('herz','blut','blutkreislauf','Herz und Gefäße bilden den Blutkreislauf.');rule('blut','wasser','niere','Die Niere filtert das Blut und bildet Harn.');
rule('photosynthese','leben','produzent','Pflanzen sind Produzenten: Sie bauen Biomasse auf.');rule('produzent','leben','konsument','Tiere fressen andere Lebewesen: Konsumenten.');rule('leben','naehrstoff','destruent','Destruenten zersetzen totes Material zu Nährstoffen.');rule('produzent','konsument','nahrungskette','Produzent → Konsument: eine Nahrungskette.');rule('nahrungskette','destruent','biozoenose','Alle Arten zusammen bilden die Biozönose.');rule('wasser','licht','biotop','Ein Biotop ist der Lebensraum der Lebewesen.');rule('biotop','biozoenose','oekosystem','Lebensraum + Lebensgemeinschaft = Ökosystem.');
rule('leben','leben','art','Eine Art: Lebewesen, die fruchtbare Nachkommen zeugen.');rule('konsument','leben','wirbeltier','Viele Konsumenten sind Wirbeltiere – mit Wirbelsäule.');rule('konsument','wasser','wirbellose','Wirbellose, z. B. Insekten, haben keine Wirbelsäule.');rule('wirbeltier','leben','saeugetier','Säugetiere säugen ihre Jungen.');rule('art','biotop','anpassung','Arten passen sich an ihren Lebensraum an.');rule('art','oekosystem','vielfalt','Viele Arten im Ökosystem ergeben Biodiversität.');
const FORMEL={photosynthese:'6 CO₂ + 6 H₂O → C₆H₁₂O₆ + 6 O₂',zellatmung:'C₆H₁₂O₆ + 6 O₂ → 6 CO₂ + 6 H₂O + Energie',staerke:'(C₆H₁₀O₅)ₙ'};
const WARUM={zellkern:'Merke: Der Zellkern enthält die DNA – den Bauplan des Lebewesens.',mitochondrium:'Merke: In den Mitochondrien wird Energie gewonnen – darum heißen sie „Kraftwerke".',pflanzenzelle:'Merke: Nur Pflanzenzellen haben Zellwand, Chloroplasten und große Vakuole.',photosynthese:'Alltag: Pflanzen „füttern" sich mit Licht und geben dabei den Sauerstoff ab, den wir atmen.',glucose:'Alltag: Traubenzucker liefert schnell Energie – nichts anderes baut die Pflanze im Blatt.',staerke:'Alltag: Kartoffeln speichern Energie als Stärke.',zellatmung:'Merke: Zellatmung ist die Umkehrung der Photosynthese – sie setzt Energie frei.',atmung:'Merke: Einatmen bringt O₂, Ausatmen entfernt CO₂.',herz:'Alltag: Dein Herz schlägt rund 100.000-mal am Tag.',produzent:'Merke: Produzenten stehen am Anfang jeder Nahrungskette.',destruent:'Alltag: Pilze und Bakterien zersetzen Laub zu Humus.',saeugetier:'Merke: Säugetiere säugen ihre Jungen mit Milch – auch der Mensch.',vielfalt:'Merke: Je mehr Arten, desto stabiler das Ökosystem.'};
const FAILHINT={};function fail(a,b,t){FAILHINT[key(a,b)]=t}
fail('sauerstoff','wasser','Sauerstoff löst sich in Wasser, aber für die Atmung brauchst du ein Lebewesen.');fail('zelle','sauerstoff','Zellen brauchen Sauerstoff für die Zellatmung – versuche lieber Glucose + Sauerstoff.');fail('kohlenstoffdioxid','wasser','CO₂ löst sich in Wasser. Für die Photosynthese brauchst du erst Chlorophyll.');fail('leben','wasser','Leben braucht Wasser – kombiniere aber gezielter, z. B. Nährstoff + Wasser für die Verdauung.');fail('licht','energie','Licht ist Energie für Pflanzen – schicke das Licht erst in einen Chloroplasten.');fail('naehrstoff','naehrstoff','Zwei Nährstoffe ergeben noch nichts Neues. Tipp: Nährstoff + Wasser startet die Verdauung.');
const MISSIONS=[['m1','Zelle erforschen','Finde Zellmembran, Zellkern und Chloroplast.',['zellmembran','zellkern','chloroplast']],['m2','Pflanzen- & Tierzelle','Baue Zellwand, Vakuole, Pflanzenzelle und Tierzelle.',['zellwand','vakuole','pflanzenzelle','tierzelle']],['m3','Photosynthese','Entdecke Chlorophyll, Photosynthese, Glucose und Stärke.',['chlorophyll','photosynthese','glucose','staerke']],['m4','Pflanzenorgane','Finde Wurzel, Blatt und Spross.',['wurzel','blatt','spross']],['m5','Der Mensch','Verbinde Atmung, Lunge, Blut, Herz und Blutkreislauf.',['atmung','lunge','blut','herz','blutkreislauf','niere']],['m6','Ökosystem','Erkläre Produzent, Konsument, Destruent und Nahrungskette.',['produzent','konsument','destruent','nahrungskette']],['m7','Lebensräume','Baue Biotop, Biozönose und Ökosystem.',['biotop','biozoenose','oekosystem']],['m8','Vielfalt','Finde Art, Wirbeltier, Säugetier, Anpassung und Biodiversität.',['art','wirbeltier','saeugetier','anpassung','vielfalt']]];
const MISSION_CAT={m1:'zelle',m2:'zelle',m3:'pflanze',m4:'pflanze',m5:'mensch',m6:'oeko',m7:'oeko',m8:'vielfalt'};
const SEEDS={zelle:['zellmembran','zellkern'],pflanze:['chlorophyll','photosynthese'],mensch:['atmung','verdauung'],oeko:['produzent','konsument'],vielfalt:['art']};
const SAVE='little-biologie8-save-v1',COINS='little-biologie8-coins-v1',QUIZ_SEEN='little-biologie8-quiz-seen-v1',XP='little-biologie8-xp-v1';let deck=[...START],selected=null,activeCat='grund',coins=5,lastRank='',xp=0,combo=0;
const $=s=>document.querySelector(s);const grid=$('#grid'),msg=$('#msg'),A=$('#slotA'),B=$('#slotB'),R=$('#slotR');
function item(id){return DATA[id]}function icon(id){return item(id)[1]}function name(id){return item(id)[0]}function info(id){return item(id)[2]}
function load(){try{deck=[...new Set([...START,...JSON.parse(localStorage.getItem(SAVE)||'[]').filter(id=>DATA[id])])];const stored=localStorage.getItem(COINS);coins=stored===null?5:Number(stored);if(!Number.isFinite(coins))coins=5;const sx=localStorage.getItem(XP);xp=sx===null?0:Number(sx);if(!Number.isFinite(xp)||xp<0)xp=0}catch(e){deck=[...START];coins=5;xp=0}combo=0;unlock(false)}
function save(){localStorage.setItem(SAVE,JSON.stringify(deck.filter(id=>!START.includes(id))));localStorage.setItem(COINS,String(coins));localStorage.setItem(XP,String(xp));schedulePush()}
const IDENT='schoolapp-ident-v1',GAME='biologie8';let cloudOn=false,ident=null,pushTimer=null;
function currentState(){return{deck:deck.filter(id=>!START.includes(id)),coins,xp}}
function applyState(s){if(!s||typeof s!=='object')return;deck=[...new Set([...START,...(Array.isArray(s.deck)?s.deck.filter(id=>DATA[id]):[])])];coins=Number.isFinite(s.coins)?s.coins:5;xp=Number.isFinite(s.xp)&&s.xp>=0?s.xp:0;combo=0;save()}
function getIdent(){try{return JSON.parse(localStorage.getItem(IDENT)||'null')}catch(e){return null}}
function setIdent(i){ident=i;localStorage.setItem(IDENT,JSON.stringify(i))}
async function cloudAvailable(){try{const c=new AbortController(),t=setTimeout(()=>c.abort(),2500);const r=await fetch('/api/ping',{signal:c.signal});clearTimeout(t);return r.ok}catch(e){return false}}
async function fetchProgress(id){try{const r=await fetch('/api/progress?code='+encodeURIComponent(id.code)+'&name='+encodeURIComponent(id.name)+'&game='+encodeURIComponent(GAME));let j={};try{j=await r.json()}catch(e){}return{status:r.status,ok:r.ok,state:j.state||null,error:j.error}}catch(e){return{status:0,ok:false,state:null}}}
function freshState(){deck=[...START];coins=5;xp=0;combo=0;save()}
function hydrate(res){if(res&&res.state&&Array.isArray(res.state.deck))applyState(res.state);else freshState()}
function finishCloud(){setAccountUI();unlock(true);lastRank=rank();resetSlots();render()}
async function push(){if(!cloudOn||!ident)return;try{await fetch('/api/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:ident.code,name:ident.name,game:GAME,state:currentState()})})}catch(e){}}
function schedulePush(){if(!cloudOn||!ident)return;clearTimeout(pushTimer);pushTimer=setTimeout(push,800)}
function setAccountUI(){const a=$('#account');if(!a)return;if(cloudOn&&ident){a.hidden=false;a.textContent='👤 '+ident.name;a.title='Klasse: '+ident.code+' · tippen zum Wechseln';a.onclick=logout}else a.hidden=true}
// Der Login kommt vom Portal: zurück zum Portal (ident wird dort gesetzt).
function logout(){localStorage.removeItem(IDENT);location.href='/'}
// Kein eigener Login mehr im Spiel – die Anmeldung erfolgt im Portal (index.html).
// Ohne gültige ident im localStorage geht es zurück zum Portal.
async function initCloud(){cloudOn=await cloudAvailable();if(!cloudOn){setAccountUI();return}ident=getIdent();if(!ident||!ident.code||!ident.name){location.href='/';return}const res=await fetchProgress(ident);if(res.status===403){localStorage.removeItem(IDENT);location.href='/';return}hydrate(res);finishCloud();toast('☁️ Angemeldet als '+ident.name)}
function setSlot(el,id,label){el.className='slot'+(id?' on':'');el.innerHTML=id?`${icon(id)}<span>${name(id)}</span><small>${info(id)}</small>`:`❔<span>${label}</span>`}
function setResult(id,ok){R.className='slot '+(ok?'ok':'bad');R.innerHTML=id?`${icon(id)}<span>${name(id)}</span>`:'✨<span>Ergebnis</span>'}
function resetSlots(){setSlot(A,null,'1. Begriff');setSlot(B,null,'2. Begriff');setResult(null,true);render()}
function missionVisible(m){const cat=MISSION_CAT[m[0]]||'grund';return cat==='grund'||deck.some(id=>CAT[id]===cat)}
function doneCount(){return MISSIONS.filter(m=>missionVisible(m)&&m[3].every(id=>deck.includes(id))).length}
function rank(){const n=doneCount();if(n>=8)return'Bio-Meister';if(n>=6)return'Ökologie-Profi';if(n>=4)return'Zell-Profi';if(n>=2)return'Bio-Starter';return'Starter'}
function progress(cat){return deck.filter(id=>CAT[id]===cat).length+' / '+Object.keys(CAT).filter(id=>CAT[id]===cat).length}
function levelOf(x){let lvl=1,need=120,acc=0;while(x>=acc+need){acc+=need;lvl++;need=Math.round(need*1.3)}return{lvl,into:x-acc,need}}
function comboMult(){return Math.max(1,Math.min(5,1+Math.floor((combo-1)/2)))}
function addXp(n){const before=levelOf(xp).lvl;xp+=n;const after=levelOf(xp).lvl;if(after>before){const bonus=after*3;coins+=bonus;toast('🎉 Level '+after+' erreicht! +'+bonus+' 🪙');confetti();setTimeout(confetti,180)}}
function unlock(store){let unlocked=[];function add(cat,cond){if(!cond)return;(SEEDS[cat]||[]).forEach(id=>{if(!deck.includes(id)){deck.push(id);if(!unlocked.includes(cat))unlocked.push(cat)}})}add('zelle',deck.includes('zellmembran')||deck.includes('zellkern')||deck.includes('chloroplast'));add('pflanze',deck.includes('chloroplast')||deck.includes('chlorophyll')||deck.includes('photosynthese'));add('mensch',deck.includes('atmung')||deck.includes('verdauung')||deck.includes('blut'));add('oeko',deck.includes('produzent')||deck.includes('konsument')||deck.includes('biotop'));add('vielfalt',deck.includes('art')||deck.includes('wirbeltier'));if(store&&unlocked.length)save();return unlocked}
function renderMissions(){const box=$('#missions');box.innerHTML='';const visible=MISSIONS.filter(missionVisible);if(!visible.length){box.innerHTML='<article class="mission"><div class="mt">🔒 Missionen gesperrt</div><div class="mi">Entdecke zuerst neue Begriffe, dann erscheinen neue Missionen.</div></article>';return}visible.forEach(m=>{const found=m[3].filter(id=>deck.includes(id)).length,ok=found===m[3].length;const el=document.createElement('article');el.className='mission '+(ok?'done':'');el.dataset.cat=MISSION_CAT[m[0]]||'grund';el.innerHTML=`<div class="mt">${ok?'✅':'🎯'} Mission: ${m[1]}</div><div class="mi">${m[2]}</div><b>${found} / ${m[3].length} entdeckt</b><div class="targets">${m[3].map(id=>`<span class="${deck.includes(id)?'done':''}">${icon(id)} ${name(id)}</span>`).join('')}</div>`;box.appendChild(el)})}
function renderLabNote(){const note=$('#labnote');if(!note)return;const n=doneCount(),total=MISSIONS.filter(missionVisible).length;note.innerHTML=`Du hast <b>${deck.length}</b> Fachkarten und <b>${n} von ${total}</b> sichtbaren Missionen geschafft.`;note.hidden=false}
function render(){const cats=Object.keys(CATEGORY).filter(c=>deck.some(id=>CAT[id]===c));if(!cats.includes(activeCat))activeCat=cats[0]||'grund';grid.innerHTML=`<div class="tabs">${cats.map(c=>`<button class="tab ${c===activeCat?'active':''}" data-cat="${c}">${CATEGORY[c]} · ${progress(c)}</button>`).join('')}</div><div class="head" data-cat="${activeCat}">${CATEGORY[activeCat]} <span>${progress(activeCat)}</span></div>`;grid.querySelectorAll('.tab').forEach(btn=>btn.onclick=()=>{activeCat=btn.dataset.cat;toast('Kategorie: '+CATEGORY[activeCat]);render()});const search=$('#search').value.toLowerCase();const cards=deck.filter(id=>CAT[id]===activeCat&&(!search||name(id).toLowerCase().includes(search)));if(!cards.length){grid.insertAdjacentHTML('beforeend','<div class="empty">Keine Karte gefunden.</div>')}cards.forEach(id=>{const el=document.createElement('article');el.className='card '+(selected===id?'sel':'');el.dataset.cat=CAT[id]||'grund';el.innerHTML=`<div class="sym">${icon(id)}</div><div class="name">${name(id)}</div><div class="info">${info(id)}</div>`;el.onclick=()=>choose(id);grid.appendChild(el)});$('#count').textContent=deck.length+' / '+Object.keys(DATA).length;$('#badge').textContent=rank();$('#coins').textContent='🪙 '+coins;const li=levelOf(xp);$('#level').textContent='⭐ Lvl '+li.lvl;$('#progressBar').style.width=Math.round(li.into/li.need*100)+'%';const cb=$('#combo');if(cb){if(combo>1){cb.textContent='🔥 Combo x'+comboMult();cb.hidden=false}else cb.hidden=true}renderMissions();renderLabNote();const r=rank();if(lastRank&&lastRank!==r){toast('🏅 Neues Abzeichen: '+r);confetti()}lastRank=r}
function choose(id){if(!selected){selected=id;setSlot(A,id);setSlot(B,null,'2. Begriff');setResult(null,true);msg.innerHTML=`<b>${icon(id)} ${name(id)}</b>: ${info(id)}<br>Wähle jetzt einen zweiten Begriff.`;render();return}setSlot(B,id);combine(selected,id);selected=null}
function combine(a,b){const result=RULES[key(a,b)];if(!result){if(combo>1)toast('💥 Combo beendet');combo=0;setResult(null,false);msg.innerHTML=smartFail(a,b);render();setTimeout(resetSlots,1050);return}combo++;const mult=comboMult();const isNew=!deck.includes(result);let gained=0;if(isNew){deck.push(result);gained=2*mult;coins+=gained;addXp(12);save()}const formula=`${name(a)} + ${name(b)} = ${name(result)}`;const explain=EXPLAIN[result]||info(result);setResult(result,true);const chem=FORMEL[result]?`<br><span class="chemformula">⚗️ ${FORMEL[result]}</span>`:'';const why=WARUM[result]?`<br><span class="why">💡 ${WARUM[result]}</span>`:'';const comboLine=mult>1?`<br><span class="comboTag">🔥 Combo x${mult}</span>`:'';const coinLine=isNew?`<br>🪙 +${gained} Münzen${mult>1?' · Combo-Bonus!':''} · +12 XP`:'';msg.innerHTML=`<b>${formula}</b>${comboLine}${chem}<br>${explain}${why}${coinLine}`;const unlocked=unlock(true);if(isNew){showUnlock(result,formula,explain);confetti()}setTimeout(()=>{resetSlots();activeCat=CAT[result]||activeCat;render();if(unlocked.length)toast('🔓 Freigeschaltet: '+unlocked.map(c=>CATEGORY[c]).join(', '))},1350)}
function smartFail(a,b){const h=FAILHINT[key(a,b)];if(h)return'🔎 '+h;if(CAT[a]!==CAT[b])return`Gute Idee. Die Begriffe liegen in <b>${CATEGORY[CAT[a]]}</b> und <b>${CATEGORY[CAT[b]]}</b>. Suche vielleicht erst einen Zwischenschritt.`;return'Noch keine passende Kombination. Denke an: Zelle, Photosynthese, Mensch, Ökologie oder Vielfalt.'}
function showUnlock(id,formula,explain){$('#pe').textContent=icon(id);$('#pt').textContent=name(id);$('#pf').textContent=formula;const chem=$('#pchem'),f=FORMEL[id];if(f){chem.textContent='⚗️ '+f;chem.hidden=false}else chem.hidden=true;$('#px').textContent=explain;const why=$('#pwhy'),w=WARUM[id];if(w){why.textContent='💡 '+w;why.hidden=false}else why.hidden=true;$('#pop').classList.add('show')}
function hint(){if(coins<3){msg.innerHTML='Ein Tipp kostet <b>3 Münzen</b>. Entdecke neue Begriffe oder spiele Bio-Blitz.';return}const possible=[];for(let i=0;i<deck.length;i++)for(let j=i;j<deck.length;j++){const c=RULES[key(deck[i],deck[j])];if(c&&!deck.includes(c))possible.push([deck[i],deck[j]])}if(!possible.length){msg.textContent='Im Moment gibt es keinen neuen Tipp.';return}coins-=3;save();const pair=possible[Math.floor(Math.random()*possible.length)];msg.innerHTML=`💡 Probiere <b>${icon(pair[0])} ${name(pair[0])}</b> + <b>${icon(pair[1])} ${name(pair[1])}</b>.`;render()}
function reset(){localStorage.removeItem(SAVE);localStorage.removeItem(COINS);localStorage.removeItem(QUIZ_SEEN);localStorage.removeItem(XP);deck=[...START];coins=5;xp=0;combo=0;selected=null;activeCat='grund';$('#search').value='';save();resetSlots();msg.innerHTML='Neustart: Du beginnst mit <b>9 Grundbegriffen</b> und <b>5 Münzen</b>.'}
const QUESTIONS=[['Wo findet die Photosynthese statt?','Chloroplast',['Chloroplast','Mitochondrium','Zellkern']],['Was steuert die Zelle?','Zellkern',['Zellkern','Vakuole','Zellwand']],['Welches Gas entsteht bei der Photosynthese?','Sauerstoff',['Sauerstoff','Kohlenstoffdioxid','Stickstoff']],['Was ist das „Kraftwerk" der Zelle?','Mitochondrium',['Mitochondrium','Chloroplast','Zellmembran']],['Welcher Zucker entsteht bei der Photosynthese?','Glucose',['Glucose','Stärke','Fett']],['Was pumpt das Blut durch den Körper?','Herz',['Herz','Lunge','Niere']],['Wo findet der Gasaustausch beim Menschen statt?','Lunge',['Lunge','Magen','Leber']],['Was sind Pflanzen im Ökosystem?','Produzenten',['Produzenten','Konsumenten','Destruenten']],['Was zersetzt totes Material?','Destruenten',['Destruenten','Produzenten','Konsumenten']],['Was haben Wirbeltiere?','Eine Wirbelsäule',['Eine Wirbelsäule','Eine Zellwand','Chloroplasten']],['Was speichert die Pflanze als Reserve?','Stärke',['Stärke','Sauerstoff','Wasser']],['Welche Zelle hat eine Zellwand?','Pflanzenzelle',['Pflanzenzelle','Tierzelle','Blutzelle']]];
function shuffle(a){return a.map(v=>[Math.random(),v]).sort((x,y)=>x[0]-y[0]).map(x=>x[1])}
function nextQuizQuestions(count=3){let seen=[];try{seen=JSON.parse(localStorage.getItem(QUIZ_SEEN)||'[]').filter(i=>Number.isInteger(i)&&i>=0&&i<QUESTIONS.length)}catch(e){seen=[]}let open=QUESTIONS.map((_,i)=>i).filter(i=>!seen.includes(i));if(open.length<count){seen=[];open=QUESTIONS.map((_,i)=>i);toast('🔁 Fragenpool neu gemischt.')}const picked=shuffle(open).slice(0,count);localStorage.setItem(QUIZ_SEEN,JSON.stringify([...new Set([...seen,...picked])]));return picked.map(i=>QUESTIONS[i])}
function quiz(){const qs=nextQuizQuestions(3);let i=0,ok=0;$('#game').classList.add('show');function ask(){const q=qs[i];$('#gs').textContent=`Frage ${i+1}/3 · richtig: ${ok}`;$('#gq').innerHTML='<h3>'+q[0]+'</h3>';$('#ga').innerHTML='';shuffle(q[2]).forEach(answer=>{const btn=document.createElement('button');btn.textContent=answer;btn.onclick=()=>{if(answer===q[1]){ok++;coins++;addXp(6);btn.className='r';$('#gs').textContent='✅ Richtig! +1 Münze · +6 XP'}else{btn.className='w';$('#gs').textContent='❌ Richtig wäre: '+q[1]}Array.from($('#ga').children).forEach(c=>c.disabled=true);setTimeout(()=>{i++;i<3?ask():finish()},850)};$('#ga').appendChild(btn)})}function finish(){if(ok===3){coins+=2;addXp(15);$('#gs').innerHTML='🏆 Perfekt! +2 Bonus-Münzen · +15 XP'}else $('#gs').textContent=`Fertig: ${ok}/3 richtig.`;save();render();if(ok===3)confetti();$('#gq').innerHTML='';$('#ga').innerHTML='<button onclick="quiz()">Nochmal spielen</button>'}ask()}
function confetti(){['🧬','🌱','✨','🍃','🐾','🔬'].forEach((x,i)=>{setTimeout(()=>{const el=document.createElement('div');el.className='confetti';el.textContent=x;el.style.left=Math.random()*96+'vw';document.body.appendChild(el);setTimeout(()=>el.remove(),1500)},i*80)})}
function toast(text){const old=document.querySelector('.toast');if(old)old.remove();const el=document.createElement('div');el.className='toast';el.textContent=text;document.body.appendChild(el);setTimeout(()=>el.remove(),2300)}
function closeModals(){document.querySelectorAll('.modal').forEach(m=>m.classList.remove('show'))}
document.addEventListener('click',e=>{if(e.target.matches('[data-close]'))e.target.closest('.modal').classList.remove('show');if(e.target.classList.contains('modal'))e.target.classList.remove('show')});
$('#hint').onclick=hint;$('#reset').onclick=reset;$('#quiz').onclick=quiz;$('#search').oninput=render;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModals()});
load();lastRank=rank();resetSlots();msg.innerHTML='Starte mit <b>9 Grundbegriffen</b>. Neue Missionen erscheinen erst, wenn du den passenden Bereich freischaltest.';initCloud();
