(function(){
  const prefersReduced=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  function ready(fn){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',fn);else fn()}
  function rectCenter(el){const r=el.getBoundingClientRect();return{x:r.left+r.width/2,y:r.top+r.height/2,w:r.width,h:r.height}}
  function addBackground(){if(prefersReduced)return;const bg=document.createElement('div');bg.className='molecule-bg';const labels=['O₂','CO₂','O₃','H₂O','CH₄','Fe'];for(let i=0;i<18;i++){const m=document.createElement('div');m.className='molecule';m.textContent=labels[i%labels.length];m.style.left=Math.random()*96+'vw';m.style.top=Math.random()*96+'vh';m.style.setProperty('--dur',(9+Math.random()*10)+'s');m.style.animationDelay=(-Math.random()*10)+'s';m.style.transform='scale('+(0.75+Math.random()*0.55)+')';bg.appendChild(m)}document.body.prepend(bg)}
  function ripple(e){const btn=e.target.closest('button');if(!btn)return;const r=btn.getBoundingClientRect();const s=Math.max(r.width,r.height);const dot=document.createElement('span');dot.className='ripple';dot.style.width=dot.style.height=s+'px';dot.style.left=(e.clientX-r.left-s/2)+'px';dot.style.top=(e.clientY-r.top-s/2)+'px';btn.appendChild(dot);setTimeout(()=>dot.remove(),650)}
  function sparks(x,y,count=12){if(prefersReduced)return;const symbols=['✨','⚛️','🧪','🔬'];for(let i=0;i<count;i++){const el=document.createElement('div');const isDot=Math.random()<.45;el.className='spark '+(isDot?'dot':'');el.textContent=isDot?'':symbols[Math.floor(Math.random()*symbols.length)];el.style.left=x+'px';el.style.top=y+'px';el.style.setProperty('--x',(Math.random()*150-75)+'px');el.style.setProperty('--y',(-30-Math.random()*115)+'px');el.style.setProperty('--c',['#ff8a28','#2364d2','#22a06b','#ffd45f'][i%4]);document.body.appendChild(el);setTimeout(()=>el.remove(),900)}}
  function beam(){if(prefersReduced)return;const a=document.querySelector('#slotA.on'),b=document.querySelector('#slotB.on'),r=document.querySelector('#slotR.ok');if(!a||!b||!r)return;const p1=rectCenter(a),p2=rectCenter(r);const dx=p2.x-p1.x,dy=p2.y-p1.y;const len=Math.hypot(dx,dy);const el=document.createElement('div');el.className='reaction-beam';el.style.left=p1.x+'px';el.style.top=(p1.y-4)+'px';el.style.width=len+'px';el.style.transform='rotate('+Math.atan2(dy,dx)+'rad)';document.body.appendChild(el);setTimeout(()=>el.remove(),750);sparks(p2.x,p2.y,16);flash()}
  function flash(){if(prefersReduced)return;const f=document.createElement('div');f.className='screen-flash';document.body.appendChild(f);setTimeout(()=>f.remove(),500)}
  function cardTilt(e){const card=e.target.closest('.card');if(!card||prefersReduced)return;const r=card.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;card.style.transform=`translateY(-3px) scale(1.01) rotateX(${(-y*6).toFixed(2)}deg) rotateY(${(x*6).toFixed(2)}deg)`}
  function cardReset(e){const card=e.target.closest('.card');if(card)card.style.transform=''}
  function observeResult(){const target=document.getElementById('slotR');if(!target)return;let last='';const obs=new MutationObserver(()=>{const txt=target.textContent;if(target.classList.contains('ok')&&txt&&txt!==last&&!txt.includes('Ergebnis')){last=txt;setTimeout(beam,40)}});obs.observe(target,{attributes:true,childList:true,subtree:true,attributeFilter:['class']})}
  function animateNewCards(){const grid=document.getElementById('grid');if(!grid||prefersReduced)return;const obs=new MutationObserver(muts=>{for(const m of muts){m.addedNodes.forEach(n=>{if(n.nodeType===1&&n.classList&&n.classList.contains('card')){n.animate([{opacity:0,transform:'translateY(10px) scale(.96)'},{opacity:1,transform:'translateY(0) scale(1)'}],{duration:260,easing:'ease-out'})}})}});obs.observe(grid,{childList:true})}
  ready(()=>{addBackground();observeResult();animateNewCards();document.addEventListener('click',ripple);document.addEventListener('pointermove',cardTilt);document.addEventListener('pointerout',cardReset);window.ChemieEffects={sparks,beam,flash}})
})();