// Little Biologie 2.0: klare Progression, 9 Startkarten, Missionen, bessere Rückmeldungen
(function(){
  const KEY='little-bio8-progress-v9';
  const OLD=['little-bio8-progress-v8','little-bio8-progress-v7','little-bio8-progress-v6','little-bio8-progress-v5','little-bio8-progress-v4','little-bio8-progress-v3','little-bio8-progress-v2','little-bio8-progress'];
  const START9=['wasser','luft','licht','nahrung','energie','lebewesen','mikroskop','reiz','lebensraum'];
  Object.assign(I,{energie:['Energie','⚡','Wird für Lebensvorgänge und Bewegung benötigt.'],leben:['Leben','🌍','Stoffwechsel, Wachstum und Reaktion auf Reize.']});
  const ORDER=['grundlagen','zellen','stoffwechsel','koerperbau','kreislauf','nerven','hormone','immun','oekologie'];
  const LABEL={grundlagen:'🌱 Grundlagen',zellen:'🔬 Zellen',stoffwechsel:'⚙️ Stoffwechsel',koerperbau:'🦴 Körperbau',kreislauf:'🫁 Atmung & Kreislauf',nerven:'🧠 Nerven & Sinne',hormone:'📡 Hormone',immun:'🛡️ Immunbiologie',oekologie:'🌳 Ökologie'};
  const SHORT={grundlagen:'🌱 Start',zellen:'🔬 Zellen',stoffwechsel:'⚙️ Stoff',koerperbau:'🦴 Körper',kreislauf:'🫁 Kreis',nerven:'🧠 Nerven',hormone:'📡 Hormone',immun:'🛡️ Immun',oekologie:'🌳 Öko'};
  const C={};
  function cat(ids,c){ids.split(' ').forEach(id=>C[id]=c)}
  cat('wasser luft licht nahrung energie lebewesen mikroskop reiz lebensraum leben pflanze tier nachweis','grundlagen');
  cat('pflanzenzelle tierzelle zelle zellbestandteil zellmembran zellplasma zellkern zellwand vakuole chloroplast mitochondrium','zellen');
  cat('fotosynthese sauerstoff zucker naehrstoff verdauungsorgan verdauung naehrstofftransport zellstoffwechsel zellatmung versorgung','stoffwechsel');
  cat('gewebe organ organsystem koerper knochen muskel skelett bewegungsapparat gegenspielerprinzip bewegung belastung haltungsschaden messung','koerperbau');
  cat('herz blut blutgefaess lunge nase atemweg atmungssystem lungenblaeschen gasaustausch sauerstofftransport kohlenstoffdioxid blutkreislauf lungenkreislauf koerperkreislauf herzfrequenz atemfrequenz blutdruck','kreislauf');
  cat('sinnesorgan auge sehen wahrnehmung nervenzelle nerv signalweiterleitung gehirn rueckenmark zns nervensystem reaktion reflex','nerven');
  cat('hormondruese hormon hormonsystem hormontransport bauchspeicheldruese insulin blutzucker blutzuckerregulation alarmreaktion','hormone');
  cat('krankheitserreger haut immunsystem impfung infektionsbarriere infektion bakterium virus immunabwehr antikoerper gedaechtniszelle immunitaet','immun');
  cat('blatt produzent konsument pilz totesmaterial destruent oekosystem abiotischerfaktor nahrungskette nahrungsnetz angepasstheit','oekologie');
  const SEEDS={koerperbau:['knochen','muskel','belastung','messung'],kreislauf:['herz','blut','blutgefaess','lunge'],nerven:['sinnesorgan','gehirn','rueckenmark'],hormone:['hormondruese','hormon','blutzucker'],immun:['krankheitserreger','haut','immunsystem','impfung'],oekologie:['pilz','totesmaterial']};
  const seedSet=new Set([...START9,...Object.values(SEEDS).flat()]);
  const MISSIONS=[
    ['m1','Mission 1: Grundlagen des Lebens','Entdecke Leben, Pflanze, Tier und Zelle.',['leben','pflanze','tier','zelle']],
    ['m2','Mission 2: Baue eine Zelle','Finde wichtige Zellbestandteile.',['zellbestandteil','zellmembran','zellplasma','zellkern','chloroplast','mitochondrium']],
    ['m3','Mission 3: Stoffwechsel','Zeige Fotosynthese und Zellatmung.',['fotosynthese','zucker','sauerstoff','naehrstoff','zellatmung']],
    ['m4','Mission 4: Vom Baustein zum Körper','Baue Zelle → Gewebe → Organ → Organsystem → Körper.',['gewebe','organ','organsystem','koerper']],
    ['m5','Mission 5: Atmung und Kreislauf','Versorge die Zellen mit Sauerstoff und Nährstoffen.',['atmungssystem','gasaustausch','blutkreislauf','sauerstofftransport','versorgung']],
    ['m6','Mission 6: Steuern und Reagieren','Verbinde Reiz, Nerven und Hormone.',['wahrnehmung','nervensystem','reaktion','hormonsystem','alarmreaktion']],
    ['m7','Mission 7: Schutz und Ökosystem','Finde Abwehr und ökologische Zusammenhänge.',['immunabwehr','immunitaet','oekosystem','nahrungskette','nahrungsnetz']]
  ];
  [['wasser','energie','leben','Ohne Wasser und Energie können Lebensvorgänge nicht ablaufen.'],['leben','lebensraum','lebewesen','Lebewesen zeigen Lebensvorgänge und leben in einem Lebensraum.'],['lebewesen','licht','pflanze','Pflanzen sind Lebewesen, die Licht nutzen können.'],['lebewesen','nahrung','tier','Tiere sind Lebewesen, die Nahrung aufnehmen.'],['nahrung','mikroskop','nachweis','Mit Nachweisen untersucht man Stoffe in Nahrung.'],['zelle','energie','mitochondrium','Mitochondrien stellen Energie bereit.'],['nahrung','nachweis','naehrstoff','Mit Nachweisen untersucht man Nährstoffe.'],['nahrung','organ','verdauungsorgan','Verdauungsorgane bearbeiten Nahrung.'],['sauerstofftransport','naehrstofftransport','versorgung','Sauerstoff und Nährstoffe gelangen zu den Zellen.'],['reiz','lebewesen','sinnesorgan','Lebewesen nehmen Reize über Sinnesorgane wahr.'],['hormondruese','blutzucker','insulin','Insulin beeinflusst den Blutzucker.'],['nahrungskette','destruent','nahrungsnetz','Destruenten ergänzen Nahrungsketten zum Nahrungsnetz.'],['lebewesen','abiotischerfaktor','angepasstheit','Lebewesen sind an Umweltfaktoren angepasst.']].forEach(x=>r(...x));
  let activeCategory='grundlagen';
  function done(id){let m=MISSIONS.find(x=>x[0]===id);return m&&m[3].every(x=>d.includes(x))}
  function discovered(){return d.filter(x=>!seedSet.has(x)).length}
  btxt=function(){if(done('m7'))return'Bio-Meister';if(done('m5'))return'System-Profi';if(done('m4'))return'Körper-Profi';if(done('m3'))return'Stoffwechsel-Profi';if(done('m2'))return'Zell-Forscher';if(discovered()>=5)return'Bio-Starter';return'Starter'};
  save=function(){localStorage.setItem(KEY,JSON.stringify(d.filter(x=>!START9.includes(x))))};
  function applyUnlock(store){let u=[];function add(cat,cond){if(!cond)return;(SEEDS[cat]||[]).forEach(id=>{if(I[id]&&!d.includes(id)){d.push(id);if(!u.includes(cat))u.push(cat)}})}add('koerperbau',d.includes('gewebe')||d.includes('organ'));add('kreislauf',d.includes('organ')||d.includes('koerper'));add('nerven',d.includes('zelle')||d.includes('wahrnehmung'));add('hormone',d.includes('koerper')||d.includes('blutkreislauf'));add('immun',d.includes('koerper')||d.includes('infektion')||d.includes('blutkreislauf'));add('oekologie',d.includes('fotosynthese')||d.includes('produzent')||d.includes('oekosystem'));if(u.length&&store)save();return u}
  function progress(cat){return d.filter(x=>C[x]===cat).length+' / '+Object.keys(C).filter(x=>C[x]===cat&&I[x]).length}
  function updateMissions(){let box=document.getElementById('missionList');if(!box)return;box.innerHTML='';MISSIONS.forEach(m=>{let found=m[3].filter(x=>d.includes(x)).length,ok=found===m[3].length,el=document.createElement('article');el.className='mission-card '+(ok?'done':found?'active':'');el.innerHTML='<div class="mission-title">'+(ok?'✅ ':'🎯 ')+m[1]+'</div><div class="mission-text">'+m[2]+'</div><div class="mission-progress">'+found+' / '+m[3].length+' entdeckt</div><div class="mission-targets">'+m[3].map(t=>'<span class="'+(d.includes(t)?'ok':'')+'">'+I[t][1]+' '+I[t][0]+'</span>').join('')+'</div>';box.appendChild(el)})}
  render=function(nid){grid.innerHTML='';let s=(search.value||'').toLowerCase(),visible=ORDER.filter(cat=>d.some(id=>C[id]===cat));if(nid&&C[nid])activeCategory=C[nid];if(!visible.includes(activeCategory))activeCategory=visible[0]||'grundlagen';let nav=document.createElement('div');nav.className='category-nav category-tabs';visible.forEach(cat=>{let btn=document.createElement('button');btn.type='button';btn.className='category-pill '+(cat===activeCategory?'active-tab':'');btn.textContent=(SHORT[cat]||LABEL[cat])+' · '+progress(cat);btn.onclick=()=>{activeCategory=cat;render();msg.innerHTML='Kategorie gewechselt: <b>'+LABEL[cat]+'</b> · Fortschritt: <b>'+progress(cat)+'</b>'};nav.appendChild(btn)});grid.appendChild(nav);let h=document.createElement('div');h.className='category-head';h.innerHTML=LABEL[activeCategory]+' <span class="category-progress">'+progress(activeCategory)+'</span>';grid.appendChild(h);let ids=d.filter(id=>C[id]===activeCategory&&(!s||I[id][0].toLowerCase().includes(s)));if(!ids.length){let e=document.createElement('div');e.className='category-empty';e.textContent=s?'Keine Karte in dieser Kategorie gefunden.':'In dieser Kategorie gibt es noch keine sichtbaren Karten.';grid.appendChild(e)}else ids.forEach(id=>{let el=document.createElement('article');el.className='card '+(sel===id?'sel ':'')+(nid===id?'new':'');el.innerHTML=card(id);el.onclick=()=>choose(id);grid.appendChild(el)});counter.textContent=d.length+' / '+Object.keys(I).length;let bt=btxt();badge.textContent=bt;if(last&&last!==bt)msg.innerHTML='🏅 Neues Abzeichen: <b>'+bt+'</b>';last=bt;updateMissions()};
  function failText(a,b){let ca=LABEL[C[a]]||'Biologie',cb=LABEL[C[b]]||'Biologie';if(C[a]!==C[b])return'Gute Idee! Die Begriffe liegen in <b>'+ca+'</b> und <b>'+cb+'</b>. Suche vielleicht erst einen Zwischenschritt.';if(a===b)return'Noch entsteht daraus nichts Neues. Manche Doppelungen funktionieren, z. B. <b>Zelle + Zelle</b> oder <b>Organ + Organ</b>.';return'Gute Idee, aber daraus entsteht noch kein neuer Fachbegriff. Überlege: Brauchst du zuerst einen Begriff aus Zelle, Körper, Stoffwechsel oder Ökosystem?'}
  combine=function(a,b){let c=R[k(a,b)];if(!c){result(null,false);msg.innerHTML=failText(a,b);setTimeout(resetSlots,1200);return}let neu=!d.includes(c);if(neu){d.push(c);save()}let f=I[a][0]+' + '+I[b][0]+' = '+I[c][0],ex=E[c]||I[c][2];result(c,true);msg.innerHTML='<b>'+f+'</b><br>'+ex;let unlocked=applyUnlock(true);if(neu)show(c,f,ex);setTimeout(()=>{resetSlots();render(neu?c:null);if(unlocked.length)msg.innerHTML='🔓 Neue Karten freigeschaltet: <b>'+unlocked.map(x=>LABEL[x]).join(', ')+'</b>'},1400)};
  hint=function(){let cur=(MISSIONS.find(m=>!m[3].every(x=>d.includes(x)))||[,,,[]])[3],p=[];for(let i=0;i<d.length;i++)for(let j=i;j<d.length;j++){let c=R[k(d[i],d[j])];if(c&&!d.includes(c))p.push([d[i],d[j],cur.includes(c)?1:0])}if(!p.length){msg.textContent='Im Moment gibt es keinen neuen Tipp.';return}p.sort((a,b)=>b[2]-a[2]);let top=p.filter(x=>x[2]===p[0][2]),x=top[Math.floor(Math.random()*top.length)];msg.innerHTML='💡 Probiere <b>'+I[x[0]][1]+' '+I[x[0]][0]+'</b> + <b>'+I[x[1]][1]+' '+I[x[1]][0]+'</b>.'};
  reset=function(){try{localStorage.removeItem(KEY);OLD.forEach(x=>localStorage.removeItem(x))}catch(e){}d=[...START9];sel=null;activeCategory='grundlagen';if(search)search.value='';save();resetSlots();msg.innerHTML='Neustart: Du beginnst mit <b>9 Grundbegriffen</b>. Entdecke zuerst Leben, Pflanze, Tier und Zelle.'};
  try{OLD.forEach(x=>localStorage.removeItem(x));let saved=JSON.parse(localStorage.getItem(KEY)||'[]').filter(x=>I[x]);d=[...new Set([...START9,...saved])]}catch(e){d=[...START9]}
  applyUnlock(false);q('#hint').onclick=hint;q('#reset').onclick=reset;last=btxt();resetSlots();msg.innerHTML='Bio-Alchemie 2.0: Starte mit <b>9 Grundbegriffen</b>. Arbeite dich über die Missionen von Leben → Zelle → Körper → Systeme → Ökologie.';
})();
